dataset.storage_id: ''
dataset.twin_id: ''
organization_id: ''
organization_url: ''
run_templates: null
scope: ''
send_scenario_metadata_to_event_hub: true
solution_id: ''
url: ''
use_dedicated_event_hub_namespace: true
workspace_id: ''
workspace_key: ''